import { pathToFileURL } from 'node:url';

import type { CsvSnapshot } from '../domain/skyscanner-matrix';

type SkyscannerModuleShape = {
  skyscannerMatrix?: unknown;
  default?: unknown;
};

function normalizeLineEnding(value: unknown): '\n' | '\r\n' {
  if (value === '\n' || value === '\r\n') {
    return value;
  }

  throw new Error(`Invalid line ending in Skyscanner module: ${String(value)}`);
}

function isStringArray(value: unknown): value is string[] {
  return Array.isArray(value) && value.every((cell) => typeof cell === 'string');
}

function freezeSnapshot(snapshot: CsvSnapshot): CsvSnapshot {
  return Object.freeze({
    hasBom: snapshot.hasBom,
    lineEnding: snapshot.lineEnding,
    trailingNewline: snapshot.trailingNewline,
    header: Object.freeze([...snapshot.header]),
    rows: Object.freeze(snapshot.rows.map((row) => Object.freeze([...row]))),
  });
}

export class TsModuleCodec {
  static render(snapshot: CsvSnapshot, exportName = 'skyscannerMatrix'): string {
    const moduleSnapshot = {
      hasBom: snapshot.hasBom,
      lineEnding: snapshot.lineEnding,
      trailingNewline: snapshot.trailingNewline,
      header: snapshot.header,
      rows: snapshot.rows,
    };

    return [
      '/**',
      ' * Generated by skyscanner from a CSV source.',
      ' * Keep this file in sync with the CSV if the source data changes.',
      ' */',
      `export const ${exportName} = ${JSON.stringify(moduleSnapshot, null, 2)} as const;`,
      `export type SkyscannerMatrixSnapshot = typeof ${exportName};`,
      '',
    ].join('\n');
  }

  static async loadSnapshot(modulePath: string, exportName = 'skyscannerMatrix'): Promise<CsvSnapshot> {
    const moduleUrl = pathToFileURL(modulePath).href;
    const loadedModule = (await import(moduleUrl)) as SkyscannerModuleShape;
    const rawSnapshot = loadedModule[exportName as keyof SkyscannerModuleShape] ?? loadedModule.default;

    if (rawSnapshot === undefined || rawSnapshot === null || typeof rawSnapshot !== 'object') {
      throw new Error(`Module ${modulePath} does not export a Skyscanner matrix snapshot`);
    }

    const snapshot = rawSnapshot as {
      hasBom?: unknown;
      lineEnding?: unknown;
      trailingNewline?: unknown;
      header?: unknown;
      rows?: unknown;
    };

    if (typeof snapshot.hasBom !== 'boolean') {
      throw new Error(`Module ${modulePath} is missing the boolean hasBom flag`);
    }

    if (typeof snapshot.trailingNewline !== 'boolean') {
      throw new Error(`Module ${modulePath} is missing the trailingNewline flag`);
    }

    if (snapshot.lineEnding !== '\n' && snapshot.lineEnding !== '\r\n') {
      throw new Error(`Module ${modulePath} is missing the lineEnding metadata`);
    }

    if (!isStringArray(snapshot.header)) {
      throw new Error(`Module ${modulePath} is missing the header array`);
    }

    if (!Array.isArray(snapshot.rows)) {
      throw new Error(`Module ${modulePath} is missing the rows array`);
    }

    const rows = snapshot.rows.map((row, rowIndex) => {
      if (!isStringArray(row)) {
        throw new Error(`Row ${rowIndex + 1} in ${modulePath} is not a string array`);
      }

      if (row.length !== snapshot.header!.length) {
        throw new Error(
          `Row ${rowIndex + 1} in ${modulePath} has ${row.length} cells but the header has ${snapshot.header!.length} columns`,
        );
      }

      return [...row];
    });

    return freezeSnapshot({
      hasBom: snapshot.hasBom,
      lineEnding: normalizeLineEnding(snapshot.lineEnding),
      trailingNewline: snapshot.trailingNewline,
      header: snapshot.header,
      rows,
    });
  }
}
